'use client';

import { useState } from 'react';
import Tesseract from 'tesseract.js';
import Image from 'next/image';
import { jsPDF } from 'jspdf';

export default function ImageTextExtractor() {
  const [image, setImage] = useState<File | null>(null);
  const [extractedText, setExtractedText] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);

  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setImage(file);
      setPreviewUrl(URL.createObjectURL(file));
      setExtractedText('');
      setError(null);
    }
  };

  const extractText = async () => {
    if (!image) {
      setError('Please upload an image first');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const result = await Tesseract.recognize(
        image,
        'eng',
        {
          logger: (m) => console.log(m),
        }
      );
      setExtractedText(result.data.text);
    } catch (err) {
      setError('Error processing image. Please try again.');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const generatePDF = () => {
    if (!extractedText) {
      setError('No text to generate PDF from. Please extract text first.');
      return;
    }

    const doc = new jsPDF();
    doc.setFont('helvetica');
    doc.setFontSize(12);

    // Split text into lines and wrap if necessary
    const lines = doc.splitTextToSize(extractedText, 180); // 180mm width with margins
    doc.text('Extracted Text from Image', 15, 15);
    doc.text(lines, 15, 25);

    // Add footer
    doc.setFontSize(10);
    doc.text('Generated by ImageTextExtractor', 15, doc.internal.pageSize.height - 10);

    // Download the PDF
    doc.save('extracted-text.pdf');
  };

  return (
    <div className="max-w-2xl mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">Image Text Extractor</h1>
      
      <div className="mb-4">
        <input
          type="file"
          accept="image/*"
          onChange={handleImageUpload}
          className="block w-full text-sm text-gray-500
            file:mr-4 file:py-2 file:px-4
            file:rounded-md file:border-0
            file:text-sm file:font-semibold
            file:bg-blue-50 file:text-blue-700
            hover:file:bg-blue-100"
        />
      </div>

      {previewUrl && (
        <div className="mb-4">
          <Image
            src={previewUrl}
            alt="Uploaded image preview"
            width={400}
            height={300}
            className="object-contain rounded-md"
          />
        </div>
      )}

      <div className="mb-4 space-x-4">
        <button
          onClick={extractText}
          disabled={isLoading || !image}
          className="px-4 py-2 bg-blue-500 text-white rounded-md
            hover:bg-blue-600 disabled:bg-gray-400 disabled:cursor-not-allowed"
        >
          {isLoading ? 'Processing...' : 'Extract Text'}
        </button>

        <button
          onClick={generatePDF}
          disabled={!extractedText}
          className="px-4 py-2 bg-green-500 text-white rounded-md
            hover:bg-green-600 disabled:bg-gray-400 disabled:cursor-not-allowed"
        >
          Download PDF
        </button>
      </div>

      {error && (
        <div className="mb-4 p-2 bg-red-100 text-red-700 rounded-md">
          {error}
        </div>
      )}

      {extractedText && (
        <div className="p-4 bg-gray-100 rounded-md">
          <h2 className="text-lg font-semibold mb-2">Extracted Text:</h2>
          <pre className="whitespace-pre-wrap">{extractedText}</pre>
        </div>
      )}
    </div>
  );
}